const CONTEXT = 'pokemon'

export const FETCH_POKEMON_REQUEST: string = `${CONTEXT}/FETCH_POKEMON_REQUEST`
export const FETCH_POKEMON_SUCCEEDED: string = `${CONTEXT}/FETCH_POKEMON_SUCCEEDED`
export const FETCH_POKEMON_FEILED: string = `${CONTEXT}/FETCH_POKEMON_FEILED`
