const CONTEXT = 'pokemon'

export const FETCH_POKEMON_REQUEST = `${CONTEXT}/FETCH_POKEMON_REQUEST`
export const FETCH_POKEMON_SUCCEEDED = `${CONTEXT}/FETCH_POKEMON_SUCCEEDED`
export const FETCH_POKEMON_FEILED = `${CONTEXT}/FETCH_POKEMON_FEILED`
